-- Sample data mirroring src/lib/data/mock.ts. Load with `supabase db reset`.
-- Extend with your real catalog; the app reads live data once these exist.

-- ─── Categories & brands ────────────────────────────────────────────────
insert into public.categories (slug, kind, title, intro, seo_paragraph, meta_title, meta_description, focus_keyword) values
('casio','brand','Casio Watches in Sri Lanka','Everyday icons — G-Shock, Edifice, Baby-G and the vintage classics.','Shop 100% authentic Casio watches in Sri Lanka, from the shock-resistant G-Shock line to the retro Vintage series and Edifice chronographs. Every piece is sourced from authorised distributors, inspected in Colombo, and delivered island-wide with a stamped manufacturer warranty.','Casio Watches Sri Lanka — Authentic G-Shock, Edifice & Vintage','Buy genuine Casio watches in Sri Lanka. G-Shock, Edifice, Baby-G and Vintage models with full warranty and island-wide delivery from Colombo.','casio watches sri lanka'),
('seiko','brand','Seiko Watches in Sri Lanka','Japanese craft — Seiko 5 Sports, Presage and Prospex.','Discover authentic Seiko watches in Sri Lanka — the automatic Seiko 5 Sports, elegant Presage dress watches and the 200m Prospex divers. Authorised stock, sealed boxes, stamped warranty cards and insured island-wide delivery from our Colombo boutique.','Seiko Watches Sri Lanka — Authentic 5 Sports, Presage & Prospex','Buy genuine Seiko watches in Sri Lanka. Seiko 5 Sports, Presage and Prospex automatics with full warranty and island-wide delivery from Colombo.','seiko watches sri lanka'),
('citizen','brand','Citizen Watches in Sri Lanka','Powered by light — Eco-Drive that never needs a battery.','Shop authentic Citizen watches in Sri Lanka, led by the light-powered Eco-Drive range and the automatic Tsuyosa. Citizen Eco-Drive models carry up to a 5-year warranty. Authorised stock, inspected in Colombo and delivered island-wide.','Citizen Watches Sri Lanka — Authentic Eco-Drive & Automatic','Buy genuine Citizen watches in Sri Lanka. Eco-Drive and automatic models with up to 5-year warranty and island-wide delivery from Colombo.','citizen watches sri lanka'),
('mens-watches','category','Men''s Watches','Automatics, divers and everyday steel for every wrist.','Browse men''s watches from Casio, Seiko and Citizen — automatic divers, dress pieces and rugged everyday steel. 100% authentic, with full manufacturer warranty and island-wide delivery across Sri Lanka.','Men''s Watches Sri Lanka — Casio, Seiko & Citizen for Men','Shop authentic men''s watches in Sri Lanka from Casio, Seiko and Citizen. Automatics, divers and dress watches with warranty and island-wide delivery.','mens watches sri lanka'),
('womens-watches','category','Women''s Watches','Refined, resilient and made to be worn every day.','Explore women''s watches from Casio Baby-G, Seiko and Citizen — refined designs built to last. Every watch is genuine, warranty-backed and delivered island-wide across Sri Lanka.','Women''s Watches Sri Lanka — Casio, Seiko & Citizen for Women','Shop authentic women''s watches in Sri Lanka from Casio Baby-G, Seiko and Citizen. Full warranty and island-wide delivery from Colombo.','womens watches sri lanka'),
('digital-watches','category','Digital Watches','LED backlights, world time and seven-year batteries.','Shop digital watches led by Casio''s legendary Vintage and G-Shock lines — LED backlights, world time, stopwatch and multi-year batteries. Genuine stock with warranty and island-wide delivery in Sri Lanka.','Digital Watches Sri Lanka — Authentic Casio Digital & G-Shock','Buy authentic digital watches in Sri Lanka. Casio Vintage and G-Shock digital models with warranty and island-wide delivery from Colombo.','digital watches sri lanka'),
('dive-watches','category','Dive Watches','100m to 200m rated — built for water.','Dive watches from Seiko Prospex, Citizen Promaster and Casio — 100m to 200m water resistance, unidirectional bezels and serious lume. Authentic, warranty-backed and delivered island-wide across Sri Lanka.','Dive Watches Sri Lanka — Seiko Prospex, Citizen Promaster','Shop authentic dive watches in Sri Lanka. Seiko Prospex and Citizen Promaster divers, 200m rated, with warranty and island-wide delivery.','dive watches sri lanka'),
('analog-watches','category','Analog Watches','Sweeping hands, sunburst dials, timeless faces.','Classic analog watches from Casio, Seiko and Citizen — sunburst dials, automatic movements and clean everyday faces. 100% genuine with full warranty and island-wide delivery in Sri Lanka.','Analog Watches Sri Lanka — Casio, Seiko & Citizen','Buy authentic analog watches in Sri Lanka from Casio, Seiko and Citizen. Automatic and quartz models with warranty and island-wide delivery.','analog watches sri lanka'),
('dress-watches','category','Dress Watches','Slim cases, leather straps, quiet elegance.','Dress watches led by the Seiko Presage and Citizen automatics — slim cases, sunburst dials and refined finishing. Authentic stock, warranty-backed and delivered island-wide across Sri Lanka.','Dress Watches Sri Lanka — Seiko Presage & Citizen','Shop authentic dress watches in Sri Lanka. Seiko Presage and Citizen automatics with warranty and island-wide delivery from Colombo.','dress watches sri lanka'),
('unisex-watches','category','Unisex Watches','Sized and styled for every wrist.','Versatile unisex watches from Casio, Seiko and Citizen — balanced case sizes and neutral styling that suits everyone. Genuine, warranty-backed and delivered island-wide in Sri Lanka.','Unisex Watches Sri Lanka — Casio, Seiko & Citizen','Buy authentic unisex watches in Sri Lanka from Casio, Seiko and Citizen. Full warranty and island-wide delivery from Colombo.','unisex watches sri lanka')
on conflict (slug) do nothing;

-- ─── Global FAQs ─────────────────────────────────────────────────────────
insert into public.faqs (question, answer, scope, position) values
('Are your watches 100% genuine?','Yes — every piece comes from an authorised distributor with a stamped manufacturer warranty card. We never sell parallel imports or open-box stock, and we''ll send you live photos of your exact watch on WhatsApp before dispatch.','global',0),
('How long does delivery take?','Colombo & suburbs: 1–2 working days. Island-wide: 2–4 working days via insured courier. Delivery is free on orders above Rs. 25,000.','global',1),
('Can I pay in instalments?','Yes — pay in 3 interest-free instalments with Koko at checkout. Cash on delivery is also available in Colombo & suburbs for orders under Rs. 150,000.','global',2),
('What warranty do I get?','The full manufacturer warranty: 1 year on Casio, Edifice and Seiko, up to 5 years on Citizen Eco-Drive. Warranty service is handled through the authorised local service centres.','global',3),
('Can I exchange or return a watch?','Unworn watches with intact tags and packaging can be exchanged within 7 days. If we shipped the wrong item or it arrives damaged, we replace it free — courier on us.','global',4)
on conflict do nothing;

-- ─── Discount codes ──────────────────────────────────────────────────────
insert into public.discount_codes (code, type, value, min_subtotal, active) values
('WELCOME10','percentage',10,25000,true),
('COLOMBO2000','fixed',2000,40000,true)
on conflict (code) do nothing;

-- ─── Page SEO defaults ───────────────────────────────────────────────────
insert into public.page_seo (page_key, h1, meta_title, meta_description, focus_keyword) values
('home',null,'Wrist Works — Authentic Casio, Seiko & Citizen Watches in Sri Lanka','Premium online watch boutique in Colombo. 100% authentic Casio, Seiko and Citizen watches with full warranty and free island-wide delivery.','authentic watches sri lanka'),
('shop','All Watches','Shop All Watches — Casio, Seiko & Citizen | Wrist Works Sri Lanka','Browse every authentic Casio, Seiko and Citizen watch in stock. Filter by brand, type and price. Full warranty and island-wide delivery from Colombo.','buy watches online sri lanka')
on conflict (page_key) do nothing;

-- Products: add your real catalog here. Example row:
-- insert into public.products (slug, name, brand, categories, price, offer_price, stock, featured, new_arrival, description)
-- values ('casio-g-shock-ga-2100-carbon-core','G-Shock GA-2100 Carbon Core','Casio','{mens-watches,analog-watches}',64500,51500,12,true,true,'…');
