// AUTO-GENERATED by scratchpad/gen_catalog.mjs — the 17-product catalog.
// Edit the generator (or the DB) rather than this file by hand.
import type { Product } from "@/types";

export const catalogProducts: Product[] = [
  {
    "id": "ga2100",
    "slug": "casio-g-shock-ga-2100-carbon-core",
    "name": "G-Shock GA-2100 Carbon Core",
    "brand": "Casio",
    "categories": [
      "mens-watches",
      "digital-watches",
      "analog-watches"
    ],
    "reference": "GA-2100-1A1",
    "description": "The GA-2100 pairs Casio's Carbon Core Guard case with a slim octagonal bezel — the 'CasiOak' silhouette that put G-Shock on every wrist. Analog-digital display, 200m water resistance and shock resistance in a package under 12mm thick.",
    "specs": null,
    "price": 64500,
    "offerPrice": 51500,
    "stock": 12,
    "featured": true,
    "newArrival": true,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
        "alt": "Casio G-Shock GA-2100 Carbon Core watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.8,
    "ratingCount": 42,
    "attributes": {
      "display": "Ana-Digi",
      "style": "Sports",
      "caseColor": "Black",
      "dial": "Black",
      "features": [
        "World Time"
      ],
      "collection": "G-Shock"
    },
    "metaTitle": "Casio G-Shock GA-2100 Carbon Core — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Casio G-Shock GA-2100 Carbon Core — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "g-shock-ga-2100-carbon-core sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-28T00:00:00Z"
  },
  {
    "id": "a168",
    "slug": "casio-vintage-a168wa-digital",
    "name": "Vintage A168WA Digital",
    "brand": "Casio",
    "categories": [
      "mens-watches",
      "digital-watches",
      "unisex-watches"
    ],
    "reference": "A168WA-1",
    "description": "The same stainless case your father wore, still under Rs. 20,000. Seven-year battery, LED backlight, and a bracelet that goes with everything from denim to a dinner jacket.",
    "specs": null,
    "price": 18500,
    "offerPrice": 14800,
    "stock": 25,
    "featured": true,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1200&q=80",
        "alt": "Casio Vintage A168WA Digital watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.9,
    "ratingCount": 88,
    "attributes": {
      "display": "Digital",
      "style": "Retro",
      "caseColor": "Silver",
      "dial": "Grey",
      "features": [],
      "collection": "A168 Series"
    },
    "metaTitle": "Casio Vintage A168WA Digital — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Casio Vintage A168WA Digital — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "vintage-a168wa-digital sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-27T00:00:00Z"
  },
  {
    "id": "ae1200",
    "slug": "casio-ae-1200-world-time-casio-royale",
    "name": "AE-1200 World Time \"Casio Royale\"",
    "brand": "Casio",
    "categories": [
      "mens-watches",
      "digital-watches",
      "unisex-watches"
    ],
    "reference": "AE-1200WHD-1A",
    "description": "The 'Casio Royale' — a world-time digital with a stainless bracelet, five daily alarms and a look that punches far above its price. Endlessly wearable, impossible to date.",
    "specs": null,
    "price": 21500,
    "offerPrice": 18200,
    "stock": 18,
    "featured": false,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=1200&q=80",
        "alt": "Casio AE-1200 World Time \"Casio Royale\" watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.8,
    "ratingCount": 56,
    "attributes": {
      "display": "Digital",
      "style": "Outdoor",
      "caseColor": "Black",
      "dial": "Grey",
      "features": [
        "World Time",
        "Multi-Dial"
      ],
      "collection": "AE Series"
    },
    "metaTitle": "Casio AE-1200 World Time \"Casio Royale\" — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Casio AE-1200 World Time \"Casio Royale\" — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "ae-1200-world-time-casio-royale sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-26T00:00:00Z"
  },
  {
    "id": "mdv106",
    "slug": "casio-mdv-106-duro-diver",
    "name": "MDV-106 Duro Diver",
    "brand": "Casio",
    "categories": [
      "mens-watches",
      "analog-watches",
      "dive-watches"
    ],
    "reference": "MDV-106-1A",
    "description": "The 'Duro' — Casio's 200m diver on a steel bracelet with a Submariner-style dial and a price that makes it the best value in dive watches. A genuine tool watch.",
    "specs": null,
    "price": 32500,
    "offerPrice": null,
    "stock": 10,
    "featured": true,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1200&q=80",
        "alt": "Casio MDV-106 Duro Diver watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.8,
    "ratingCount": 47,
    "attributes": {
      "display": "Analog",
      "style": "Dive",
      "caseColor": "Black",
      "dial": "Black",
      "features": [],
      "collection": "MDV Series"
    },
    "metaTitle": "Casio MDV-106 Duro Diver — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Casio MDV-106 Duro Diver — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "mdv-106-duro-diver sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-25T00:00:00Z"
  },
  {
    "id": "mtp1375",
    "slug": "casio-mtp-1375-classic-analog",
    "name": "MTP-1375 Classic Analog",
    "brand": "Casio",
    "categories": [
      "mens-watches",
      "analog-watches",
      "dress-watches"
    ],
    "reference": "MTP-1375D-1AV",
    "description": "A clean, slim dress analog with a sunburst dial and date window — the easiest way to smarten up a shirt without spending a fortune.",
    "specs": null,
    "price": 24500,
    "offerPrice": 19900,
    "stock": 15,
    "featured": false,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=80",
        "alt": "Casio MTP-1375 Classic Analog watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.6,
    "ratingCount": 22,
    "attributes": {
      "display": "Analog",
      "style": "Dress",
      "caseColor": "Silver",
      "dial": "White",
      "features": [],
      "collection": "MTP Series"
    },
    "metaTitle": "Casio MTP-1375 Classic Analog — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Casio MTP-1375 Classic Analog — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "mtp-1375-classic-analog sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-24T00:00:00Z"
  },
  {
    "id": "ca53",
    "slug": "casio-ca-53w-databank-calculator",
    "name": "CA-53W Databank Calculator",
    "brand": "Casio",
    "categories": [
      "mens-watches",
      "digital-watches",
      "unisex-watches"
    ],
    "reference": "CA-53W-1",
    "description": "The original calculator watch. Retro resin case, working databank calculator and the geek-chic charm that never really left. As worn on screen and off.",
    "specs": null,
    "price": 16800,
    "offerPrice": null,
    "stock": 20,
    "featured": false,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&w=1200&q=80",
        "alt": "Casio CA-53W Databank Calculator watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.9,
    "ratingCount": 61,
    "attributes": {
      "display": "Digital",
      "style": "Retro",
      "caseColor": "Black",
      "dial": "Grey",
      "features": [
        "Calculator"
      ],
      "collection": "Databank"
    },
    "metaTitle": "Casio CA-53W Databank Calculator — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Casio CA-53W Databank Calculator — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "ca-53w-databank-calculator sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-23T00:00:00Z"
  },
  {
    "id": "bga280",
    "slug": "casio-baby-g-bga-280-tonal",
    "name": "Baby-G BGA-280 Tonal",
    "brand": "Casio",
    "categories": [
      "womens-watches",
      "digital-watches",
      "analog-watches"
    ],
    "reference": "BGA-280-4A",
    "description": "A slim ana-digi Baby-G in a soft tonal colourway — shock resistant, 100m water resistant, and sized for smaller wrists. World time, stopwatch and the toughness Baby-G is known for.",
    "specs": null,
    "price": 48500,
    "offerPrice": 38800,
    "stock": 0,
    "featured": false,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?auto=format&fit=crop&w=1200&q=80",
        "alt": "Casio Baby-G BGA-280 Tonal watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.7,
    "ratingCount": 21,
    "attributes": {
      "display": "Ana-Digi",
      "style": "Casual",
      "caseColor": "Black",
      "dial": "White",
      "features": [
        "World Time"
      ],
      "collection": "Baby-G"
    },
    "metaTitle": "Casio Baby-G BGA-280 Tonal — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Casio Baby-G BGA-280 Tonal — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "baby-g-bga-280-tonal sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-22T00:00:00Z"
  },
  {
    "id": "efv100",
    "slug": "edifice-edifice-efv-100d-chronograph",
    "name": "Edifice EFV-100D Chronograph",
    "brand": "Edifice",
    "categories": [
      "mens-watches",
      "analog-watches"
    ],
    "reference": "EFV-100D-2AV",
    "description": "Edifice motorsport DNA in a slim steel chronograph — three sub-dials, a tachymeter bezel and a blue sunburst dial that catches the light.",
    "specs": null,
    "price": 42500,
    "offerPrice": null,
    "stock": 8,
    "featured": false,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1495856458515-0637185db551?auto=format&fit=crop&w=1200&q=80",
        "alt": "Edifice Edifice EFV-100D Chronograph watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.7,
    "ratingCount": 29,
    "attributes": {
      "display": "Analog",
      "style": "Sports",
      "caseColor": "Silver",
      "dial": "Blue",
      "features": [
        "Chronograph"
      ],
      "collection": "Edifice EFV"
    },
    "metaTitle": "Edifice Edifice EFV-100D Chronograph — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Edifice Edifice EFV-100D Chronograph — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "edifice-efv-100d-chronograph sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-21T00:00:00Z"
  },
  {
    "id": "ecb2000",
    "slug": "edifice-edifice-ecb-2000-bluetooth",
    "name": "Edifice ECB-2000 Bluetooth",
    "brand": "Edifice",
    "categories": [
      "mens-watches",
      "digital-watches",
      "analog-watches"
    ],
    "reference": "ECB-2000D-1A",
    "description": "Edifice's Bluetooth chronograph links to your phone for world time across 300+ cities, with Tough Solar power and a carbon-look dial.",
    "specs": null,
    "price": 108000,
    "offerPrice": 96500,
    "stock": 6,
    "featured": true,
    "newArrival": true,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=1200&q=80",
        "alt": "Edifice Edifice ECB-2000 Bluetooth watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.8,
    "ratingCount": 33,
    "attributes": {
      "display": "Ana-Digi",
      "style": "Sports",
      "caseColor": "Black",
      "dial": "Black",
      "features": [
        "Chronograph",
        "World Time",
        "Multi-Dial"
      ],
      "collection": "Edifice ECB"
    },
    "metaTitle": "Edifice Edifice ECB-2000 Bluetooth — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Edifice Edifice ECB-2000 Bluetooth — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "edifice-ecb-2000-bluetooth sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-20T00:00:00Z"
  },
  {
    "id": "srpd55",
    "slug": "seiko-5-sports-srpd55-automatic",
    "name": "5 Sports SRPD55 Automatic",
    "brand": "Seiko",
    "categories": [
      "mens-watches",
      "analog-watches"
    ],
    "reference": "SRPD55K3",
    "description": "The SRPD55 carries the 5 Sports line's SKX heritage — a black sunburst dial, day-date at three, and LumiBrite hands that stay legible long after sunset. The 4R36 automatic hand-winds and hacks, and the 100m rating handles a swim without a second thought.",
    "specs": null,
    "price": 118000,
    "offerPrice": 94500,
    "stock": 6,
    "featured": true,
    "newArrival": true,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
        "alt": "Seiko 5 Sports SRPD55 Automatic watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.9,
    "ratingCount": 63,
    "attributes": {
      "display": "Analog",
      "style": "Sports",
      "caseColor": "Black",
      "dial": "Black",
      "features": [
        "Automatic"
      ],
      "collection": "5 Sports"
    },
    "metaTitle": "Seiko 5 Sports SRPD55 Automatic — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Seiko 5 Sports SRPD55 Automatic — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "5-sports-srpd55-automatic sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-19T00:00:00Z"
  },
  {
    "id": "srpb43",
    "slug": "seiko-presage-cocktail-time-srpb43",
    "name": "Presage Cocktail Time SRPB43",
    "brand": "Seiko",
    "categories": [
      "mens-watches",
      "analog-watches",
      "dress-watches"
    ],
    "reference": "SRPB43J1",
    "description": "Seiko's Presage Cocktail Time turns a bar in Ginza into a dial. Hand-finished sunburst blue, 4R35 movement, and a presence far beyond its price. Our pick for a first proper automatic.",
    "specs": null,
    "price": 168000,
    "offerPrice": null,
    "stock": 3,
    "featured": true,
    "newArrival": true,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1200&q=80",
        "alt": "Seiko Presage Cocktail Time SRPB43 watch",
        "position": 0
      }
    ],
    "ratingAverage": 5,
    "ratingCount": 24,
    "attributes": {
      "display": "Analog",
      "style": "Dress",
      "caseColor": "Silver",
      "dial": "Blue",
      "features": [
        "Automatic"
      ],
      "collection": "Presage"
    },
    "metaTitle": "Seiko Presage Cocktail Time SRPB43 — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Seiko Presage Cocktail Time SRPB43 — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "presage-cocktail-time-srpb43 sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-18T00:00:00Z"
  },
  {
    "id": "srpe93",
    "slug": "seiko-prospex-srpe93-turtle-diver",
    "name": "Prospex SRPE93 Turtle Diver",
    "brand": "Seiko",
    "categories": [
      "mens-watches",
      "analog-watches",
      "dive-watches"
    ],
    "reference": "SRPE93K1",
    "description": "The cushion-cased 'Turtle' is a modern dive icon — 200m rated, day-date, and lume you could read from across the room. 4R36 automatic with hacking and hand-winding.",
    "specs": null,
    "price": 152000,
    "offerPrice": 129000,
    "stock": 5,
    "featured": false,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=1200&q=80",
        "alt": "Seiko Prospex SRPE93 Turtle Diver watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.9,
    "ratingCount": 37,
    "attributes": {
      "display": "Analog",
      "style": "Dive",
      "caseColor": "Black",
      "dial": "Black",
      "features": [
        "Automatic"
      ],
      "collection": "Prospex"
    },
    "metaTitle": "Seiko Prospex SRPE93 Turtle Diver — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Seiko Prospex SRPE93 Turtle Diver — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "prospex-srpe93-turtle-diver sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-17T00:00:00Z"
  },
  {
    "id": "sur497",
    "slug": "seiko-essentials-sur497-quartz",
    "name": "Essentials SUR497 Quartz",
    "brand": "Seiko",
    "categories": [
      "mens-watches",
      "analog-watches",
      "dress-watches"
    ],
    "reference": "SUR497P1",
    "description": "A gold-tone quartz dress watch with a crisp white dial — understated, sharp, and ready for anything from the office to a wedding.",
    "specs": null,
    "price": 78500,
    "offerPrice": 66900,
    "stock": 9,
    "featured": false,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1200&q=80",
        "alt": "Seiko Essentials SUR497 Quartz watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.6,
    "ratingCount": 15,
    "attributes": {
      "display": "Analog",
      "style": "Dress",
      "caseColor": "Gold",
      "dial": "White",
      "features": [],
      "collection": "Essentials"
    },
    "metaTitle": "Seiko Essentials SUR497 Quartz — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Seiko Essentials SUR497 Quartz — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "essentials-sur497-quartz sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-16T00:00:00Z"
  },
  {
    "id": "bm8180",
    "slug": "citizen-eco-drive-bm8180-field",
    "name": "Eco-Drive BM8180 Field",
    "brand": "Citizen",
    "categories": [
      "mens-watches",
      "analog-watches"
    ],
    "reference": "BM8180-03E",
    "description": "A do-everything field watch powered by light — never needs a battery. Green dial, 37mm case and a canvas strap that suits jeans as easily as chinos. Citizen's Eco-Drive runs for months on a full charge.",
    "specs": null,
    "price": 56500,
    "offerPrice": 47900,
    "stock": 9,
    "featured": true,
    "newArrival": true,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=80",
        "alt": "Citizen Eco-Drive BM8180 Field watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.7,
    "ratingCount": 31,
    "attributes": {
      "display": "Analog",
      "style": "Outdoor",
      "caseColor": "Black",
      "dial": "Black",
      "features": [
        "Solar"
      ],
      "collection": "Eco-Drive"
    },
    "metaTitle": "Citizen Eco-Drive BM8180 Field — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Citizen Eco-Drive BM8180 Field — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "eco-drive-bm8180-field sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-15T00:00:00Z"
  },
  {
    "id": "bn0150",
    "slug": "citizen-promaster-diver-bn0150",
    "name": "Promaster Diver BN0150",
    "brand": "Citizen",
    "categories": [
      "mens-watches",
      "analog-watches",
      "dive-watches"
    ],
    "reference": "BN0150-28E",
    "description": "The Promaster diver — 200m rated, ISO-certified, Eco-Drive powered. A serious dive tool that never needs a battery.",
    "specs": null,
    "price": 98500,
    "offerPrice": 82500,
    "stock": 0,
    "featured": false,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&w=1200&q=80",
        "alt": "Citizen Promaster Diver BN0150 watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.9,
    "ratingCount": 44,
    "attributes": {
      "display": "Analog",
      "style": "Dive",
      "caseColor": "Black",
      "dial": "Black",
      "features": [
        "Solar"
      ],
      "collection": "Promaster"
    },
    "metaTitle": "Citizen Promaster Diver BN0150 — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Citizen Promaster Diver BN0150 — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "promaster-diver-bn0150 sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-14T00:00:00Z"
  },
  {
    "id": "nj0150",
    "slug": "citizen-tsuyosa-nj0150-automatic",
    "name": "Tsuyosa NJ0150 Automatic",
    "brand": "Citizen",
    "categories": [
      "mens-watches",
      "analog-watches",
      "unisex-watches"
    ],
    "reference": "NJ0150-81X",
    "description": "Citizen's answer to the integrated-bracelet sports watch. A sunray blue dial, faceted indices and an automatic movement visible through the display back — presence far above its price.",
    "specs": null,
    "price": 112000,
    "offerPrice": null,
    "stock": 4,
    "featured": true,
    "newArrival": true,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?auto=format&fit=crop&w=1200&q=80",
        "alt": "Citizen Tsuyosa NJ0150 Automatic watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.8,
    "ratingCount": 18,
    "attributes": {
      "display": "Analog",
      "style": "Casual",
      "caseColor": "Silver",
      "dial": "Blue",
      "features": [
        "Automatic"
      ],
      "collection": "Tsuyosa"
    },
    "metaTitle": "Citizen Tsuyosa NJ0150 Automatic — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Citizen Tsuyosa NJ0150 Automatic — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "tsuyosa-nj0150-automatic sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-13T00:00:00Z"
  },
  {
    "id": "ew5551",
    "slug": "citizen-l-ambiluna-ew5551",
    "name": "L Ambiluna EW5551",
    "brand": "Citizen",
    "categories": [
      "womens-watches",
      "analog-watches",
      "dress-watches"
    ],
    "reference": "EW5551-56D",
    "description": "The L Ambiluna — a refined two-tone Eco-Drive for the wrist that likes a little shimmer. Light powered, mother-of-pearl accents, everyday elegance.",
    "specs": null,
    "price": 89500,
    "offerPrice": 74500,
    "stock": 7,
    "featured": false,
    "newArrival": false,
    "images": [
      {
        "url": "https://images.unsplash.com/photo-1495856458515-0637185db551?auto=format&fit=crop&w=1200&q=80",
        "alt": "Citizen L Ambiluna EW5551 watch",
        "position": 0
      }
    ],
    "ratingAverage": 4.8,
    "ratingCount": 12,
    "attributes": {
      "display": "Analog",
      "style": "Dress",
      "caseColor": "Two-Tone",
      "dial": "White",
      "features": [
        "Solar"
      ],
      "collection": "Eco-Drive"
    },
    "metaTitle": "Citizen L Ambiluna EW5551 — Buy Authentic in Sri Lanka",
    "metaDescription": "Genuine Citizen L Ambiluna EW5551 — 100% authentic with full warranty and island-wide delivery in Sri Lanka.",
    "focusKeyword": "l-ambiluna-ew5551 sri lanka",
    "ogImage": null,
    "createdAt": "2026-06-12T00:00:00Z"
  }
];
